---
- hosts:  UAT-servers
  tasks:
    - name: log into docker hub registry
      docker_login:
        email: "santosh.pn459@gmail.com"
        username: "santu458"
        password: "dckr_pat_u065r_4Qrq4CojzPVCPZh4LUQ8w"
    - name: Pull the image from docker hub
      shell: docker pull santu459/webappsantu:14
    - name: Run the container using the Image
      shell: docker run --name=santuspringboot-p 8080:8080 --detach santu459/webappsantu:14
